services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.29.2
    - secure: "KVfw61MWYGQtY70Y1bWgU+65kP2mVVlPcte9RB9hUCoXcfd0RaNeH11lG0hjNkn/TjZdZ0XEmNIoSa/yOqIZ13KXejAeTE2oqoh2Ta1Ue2tSbeF2GE9/JXmP+SNOlM+tOyn0tneLL39L/5Uhx/9rQi9Qwr7cprnZil+SFGRYsHnDWlZHMA0R2f2PlrreBiVVyvaNoerayT9gvyFtkObaPgrIH5a/D2eFFjyVUxttykjVfpRj7Gd8gU9FR8/NXxAFGSgE7le1o53udqnnNlH7OhLlWlM9lHHGwxyf8NGreZJ5TVT+rc68MsLjlAC3cc7O9DYEXsq6OTDVZApuUzwtKbhwDTe3YrHzj/RKcfU6R7whAjg5vZO7coZz01npWqNahi7i+oAV5kN6IBlmtt64F4CxCIEZeE4IR0zvLCcQMY/1ZqFxywx2+fQM7mIZVDLAuQAav3h7tU0yF6AfByF8QPBafpk7uhBJPY1/2vZTTxANB0q+ikpunzaxvVM1uYHuF60E3Yq9U2YXyxXxiEb4g7C7daFFrmywybOcKWKaN6cGrXSwl0tatP9DzmS/yrirhiqDt5ZiTVXExMQUjSlrW6xidoLzYhTX5wdw0BK+9MHrZ+FkdjByb6Tl2H7zKjJhIXm1t+Q+kJJefIJQz9pAwWWzZ3uXMCouGZ4OPfsTNnc="
    - secure: "aK187nbfhtnXP2MXFlu8Gq6fy371iDPb29fYjFhLVxKhq7AIcpAfiL7/2ynjQEIliRMjjpotYPYkECqoGh10rGrQx7U76KbGnDyO5uiE0oIiB+cR/eafGh67LzUvIYLb7GXhCx4IKMKxYt0AMaeoF6Q4LVLJCkJe7VpYn7W8tPH6jNK+1AOfuCKfgPQRnJxm1+i0wmViyPhVyNEXAQIwsK0CT6nM3DSB6AalbaLLyEuuXzIBgpWF6pR5MrU/50QxtxHa7Ubo8LrVbTPE1lzEEaPPZZQc/zSv/xHvPiXXHkhjD4hQ8wgpPaM4z25i45vzEquyVpi1GWAbHpkw/JnTbq8wMY2nhyRDhpKYmTApJa9vWFSP26f7hssGsYjftkunrCXHwHOHGBn5vVnje6TAtvR70Q/B8ORpOd39eEXZZE9KPIMPsnRmgQQpMbGIK80p7d1eb0JzSbBVQn6jkz2RVcFz71aKX5OmZgLC4ta7b/LANQeYAaHn4brgzCdkZT0tDMRL9j3pPwlKPq4SIt8SCXKWeFwXtstdzwh9kgn9UcMhOM/Ad/nZaMa30tqBYU5QXAC15/htLZ3tWW0qu64ULQwax45oQZEC8aYu7/9CSJJ5UaEl5h3NNes4woZgrCXbRMunHLtOWx2SFjNJJvOxBJOzFD0XQtw1W7BNAfy1/Bo="

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version
  - echo "Loging into Docker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
        - docker-compose -f ./docker/compose/docker-compose.yml -f ./docker/compose/docker-compose.test.yml run --rm --no-deps application sh -c "pytest /var/www/tests/unit"
    - stage: tests
      name: "Static Analysis"
      script:
        - docker-compose -f ./docker/compose/docker-compose.yml -f ./docker/compose/docker-compose.test.yml run --rm --no-deps static-analysis
    - stage: push
      script:
        - docker-compose -f ./docker/compose/docker-compose.yml -f ./docker/compose/docker-compose.production.yml build application
        - docker tag nlpemagistercom_application:latest fdelgados/nlpemagistercom_application:latest:$TRAVIS_BRANCH
      deploy:
      - provider: script
        script: docker push fdelgados/nlpemagistercom_application:latest:$TRAVIS_BRANCH
        on:
          branch: master
      - provider: script
        script: docker push fdelgados/nlpemagistercom_application:latest:$TRAVIS_BRANCH
        on:
          tags: true
