services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.29.2
    - secure: "KVfw61MWYGQtY70Y1bWgU+65kP2mVVlPcte9RB9hUCoXcfd0RaNeH11lG0hjNkn/TjZdZ0XEmNIoSa/yOqIZ13KXejAeTE2oqoh2Ta1Ue2tSbeF2GE9/JXmP+SNOlM+tOyn0tneLL39L/5Uhx/9rQi9Qwr7cprnZil+SFGRYsHnDWlZHMA0R2f2PlrreBiVVyvaNoerayT9gvyFtkObaPgrIH5a/D2eFFjyVUxttykjVfpRj7Gd8gU9FR8/NXxAFGSgE7le1o53udqnnNlH7OhLlWlM9lHHGwxyf8NGreZJ5TVT+rc68MsLjlAC3cc7O9DYEXsq6OTDVZApuUzwtKbhwDTe3YrHzj/RKcfU6R7whAjg5vZO7coZz01npWqNahi7i+oAV5kN6IBlmtt64F4CxCIEZeE4IR0zvLCcQMY/1ZqFxywx2+fQM7mIZVDLAuQAav3h7tU0yF6AfByF8QPBafpk7uhBJPY1/2vZTTxANB0q+ikpunzaxvVM1uYHuF60E3Yq9U2YXyxXxiEb4g7C7daFFrmywybOcKWKaN6cGrXSwl0tatP9DzmS/yrirhiqDt5ZiTVXExMQUjSlrW6xidoLzYhTX5wdw0BK+9MHrZ+FkdjByb6Tl2H7zKjJhIXm1t+Q+kJJefIJQz9pAwWWzZ3uXMCouGZ4OPfsTNnc="
    - secure: "Vpn+KFMavohAizUfItUYvLphL03QT7uvAvdcUAB5g3BZBSCv9EmQVOYwqq8+GnUq4XqekXcRYCGATpPju6n5cUsyGUj7MuFN/llTPh0N/NS4zCTND68yyVezEJGn8oh+QZc3NTZtOp+cTwijrES6UOvwVs1japvd1EW6aQqaSzrkcXIV2+o2rYiZpMzVUYbA3R/TE3ZJ4aSH6fEfC+H4NP6w/E5OvABbFshfLTtkFsPW1peOBZ+tHFG/0Jp1FEF1T1uPB6U1kUIyWwc0EtmXSR9A4Df5YRMrEWoH4ACkGD7aB4pmJyv1setuyGhecq/mwtjH38BSA5C3/TjmpG3kZSelOghf0N7xtdwZnYgG2kD6/HFSgmILOVK9Nz4WHUN09t51nGIuzdkH0/7nn1nnOUv0Ke3Pp+g4VZYXth1oHSPSRRwC4Okc9Q+k480vlmivNHFYwCrt3DgTg1On6GnuLt/kfXD2+2Usp9n17ETh0nnZkrG95P88C6Trjp39E4cJfeu//64ED/NPJZVOjtiFGFRSsIuJFepZ+b1oMV379Zk7O62FX5u4eRJ7QWT8Zrie1kfSzx/CsayTLeK+ZWNInlgly25EUAQhXmwa0DAH1jj3I3odY59XG30fbBLuRjqPv3ErMfTLEqf0ZoePWv4dD0SkjYkq/rm/q5OVOafO40A="

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version
  - echo "Loging into Docker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
        - docker-compose -f ./docker/compose/docker-compose.yml -f ./docker/compose/docker-compose.test.yml run --rm --no-deps application sh -c "pytest /var/www/tests/unit"
    - stage: tests
      name: "Static Analysis"
      script:
        - docker-compose -f ./docker/compose/docker-compose.yml -f ./docker/compose/docker-compose.test.yml run --rm --no-deps static-analysis
    - stage: push
      script:
        - docker-compose -f ./docker/compose/docker-compose.yml -f ./docker/compose/docker-compose.production.yml build application
        - docker tag nlpemagistercom_application:latest fdelgados/nlpemagistercom_application:$TRAVIS_BRANCH
      deploy:
      - provider: script
        script: docker push fdelgados/nlpemagistercom_application:$TRAVIS_BRANCH
        on:
          branch: master
      - provider: script
        script: docker push fdelgados/nlpemagistercom_application:$TRAVIS_BRANCH
        on:
          tags: true
