version: "3"

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: etl-pipeline-launcher-mysql
    image: mysql-server:latest
    networks:
      etl_pipeline_launcher:
        ipv4_address: 10.5.0.3
    volumes:
      - ./.mysql-data:/var/lib/mysql/
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=HyMn4q6UR6wa
    command: --default-authentication-plugin=mysql_native_password

  #  redis_pubsub:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    image: websitecorpus-image
  #    depends_on:
  #      - mysql
  #      - redis
  #      - mailhog
  #    environment:
  #      - DB_USER=root
  #      - DB_HOST=
  #      - DB_PASSWORD=
  #      - REDIS_HOST=redis
  #      - EMAIL_HOST=mailhog
  #      - PYTHONDONTWRITEBYTECODE=1
  #    volumes:
  #      - ./src:/src
  #      - ./tests:/tests
  #    entrypoint:
  #      - python
  #      - /src/corpus/entrypoints/redis_eventconsumer.py

  application:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    depends_on:
      - mysql
      - rabbitmq
      #      - redis_pubsub
      - mailhog
      - mongo
      - mongo-express
    networks:
      etl_pipeline_launcher:
        ipv4_address: 10.5.0.2
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=shared/infrastructure/entrypoint/flask/start.py
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"

  rabbitmq:
    container_name: etl-pipeline-launcher-rabbitmq
    hostname: rabbitmq-server
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=yvPZ6j9n4ZyhXJV2
    networks:
      etl_pipeline_launcher:
        ipv4_address: 10.5.0.5
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: etl-pipeline-launcher-redis
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    hostname: redis
    networks:
      etl_pipeline_launcher:
        ipv4_address: 10.5.0.4
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/redis-data

  mailhog:
    container_name: etl-pipeline-launcher-mail
    image: mailhog/mailhog
    networks:
      etl_pipeline_launcher:
        ipv4_address: 10.5.0.6
    ports:
      - "11025:1025"
      - "18025:8025"

  mongo:
    image: mongo:3.1
    container_name: etl-pipeline-launcher-mongodb
    restart: always
    networks:
      etl_pipeline_launcher:
        ipv4_address: 10.5.0.7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-express:
    image: mongo-express:0.32
    container_name: etl-pipeline-launcher-mongo-express
    restart: always
    networks:
      etl_pipeline_launcher:
        ipv4_address: 10.5.0.8
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example

networks:
  etl_pipeline_launcher:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
