version: "3"

services:
  application:
    environment:
      - ENVIRONMENT=development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./config:/var/www/config
      - ./export:/export
      - ./log:/log
      - ./bin:/var/www/bin
    ports:
      - "5000:5000"

  worker:
    environment:
      - ENVIRONMENT=development
