version: "3"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LAUNCHER_DB_USER=launcher
      - LAUNCHER_DB_PASSWORD=wTUbtEmk2S6R
      - API_HOST=localhost
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./config:/config
      - ./export:/export
      - ./log:/log
    ports:
      - "5000:5000"
