[application]
baseurl = "http://localhost"
id = "fc050f989329b47f861e5760c713c820"
root_dir = "/opt/code"
logs_dir = "/opt/code/log"
contexts_dir = "/opt/code/src"
configs_dir = "/opt/code/config"
store_domain_event_subscriber.id = "shared.application.event.store.store_domain_event_on_published"
store_domain_event_subscriber.class_name = "shared.application.event.store.StoreDomainEventOnPublished"
contexts.corpus.event_store.enabled = true
contexts.corpus.event_store.id = "corpus.domain.event.event_store.event_store"
contexts.duplicates.event_store.enabled = true
contexts.duplicates.event_store.id = "duplicates.domain.event.event_store.event_store"

[identity_access]
token_issuer = "http://localhost"
public_key_file = "/opt/code/export/certs/identity_access.pem"
verify_token_expiration_time = false

[api]
title = "Corpus Builder API"
port = 5000
prefix = "/corpus-builder/api/v{:d}"
version_str = "v{:d}"
version = 1
doc_path = "/corpus-builder/api/doc"

[mariadb]
wait_timeout = 500

[redis]
databases.cache = 0
databases.corpus_config = 1

[rabbitmq]
exchanges.publish = "build_pipeline"
connection.vhost = "/"

[flask]
error_include_message = false
flask_debug = false

[duplicates]
content_file = "/opt/code/data/{}/{}/content.csv"
minhashes_file = "/opt/code/data/{}/{}/minhashes.pkl"
