version: "3"

services:
  mariadb:
    image: mariadb:10.4.21
    restart: always
    environment:
      - MYSQL_ROOT_HOST
      - MYSQL_ROOT_PASSWORD
    ports:
      - "${MARIA_DB_EXTERNAL_PORT}:3306"
    volumes:
      - ../resources/databases:/docker-entrypoint-initdb.d
      - ../.mariadb-data-${SITE}:/var/lib/mysql

  application:
    image: nlp-${SITE}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - REQUIREMENTS_FILE=${REQUIREMENTS_FILE}
    depends_on:
      - mariadb
      - rabbitmq
      - redis
      - mailhog
      - mongo
      - mongo-express
    volumes:
      - ../src:/var/www/src
      - ../tests:/var/www/tests
      - ../config:/var/www/config
      - ../export:/export
      - ../log:/log
      - ../bin:/var/www/bin
      - ../.data:/var/www/data
    restart: always
#    env_file:
#      - ./vars.env
    environment:
      - FLASK_APP
      - PYTHONDONTWRITEBYTECODE
      - PYTHONUNBUFFERED
      - ENVIRONMENT
      - FLASK_ENV
      - FLASK_DEBUG
      - SITE
      - MARIA_DB_HOST
      - DUPLICATES_DATABASE_NAME
      - DUPLICATES_DATABASE_USER
      - DUPLICATES_DATABASE_PASSWORD
      - CORPUS_DATABASE_NAME
      - CORPUS_DATABASE_USER
      - CORPUS_DATABASE_PASSWORD
      - REDIS_PORT
      - REDIS_HOST
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_USER
      - MONGO_INITDB_PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
    ports:
      - "${APPLICATION_PORT}:5000"
    command: gunicorn --bind 0.0.0.0:5000 shared.infrastructure.flask.entrypoint.run:app

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /var/www/bin/run_workers.py
    depends_on:
      - rabbitmq
      - redis
      - mailhog
      - mongo
      - mongo-express
    environment:
      - ENVIRONMENT
      - SITE

  static-analysis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: flake8 --ignore=E203,W503 .
    environment:
      - REQUIREMENTS_FILE

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
    ports:
      - "${RABBITMQ_EXTERNAL_PORT}:5672"
      - "${RABBITMQ_GUI_PORT}:15672"

  redis:
    image: redis:3.2.12
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - ../.redis-data-${SITE}:/redis-data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_EXTERNAL_PORT}:1025"
      - "${MAILHOG_EXTERNAL_PORT_2}:8025"

  mongo:
    image: mongo:5.0-focal
    restart: always
    ports:
      - "${MONGO_EXTERNAL_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_USER
      - MONGO_INITDB_PASSWORD
    volumes:
      - ../resources/mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ../.mongodb-data-${SITE}:/data/db

  mongo-express:
    image: mongo-express:0.32
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_URL
