[application]
timezone = "Europe/Madrid"

[mongodb]
databases.web_corpus = "web_corpus_es"

[database]
host = "nlp.mysql.emagister.com"
[database.corpus]
  name = "corpus"
  user = "corpus"
  password = "wTUbtEmk2S6R"
