[application]
id = "fc050f989329b47f861e5760c713c820"
root_dir = "/"
logs_dir = "/log"
contexts_dir = "/src"

[identity_access]
token_issuer = "http://localhost"
public_key_file = "/export/certs/identity_access.pem"

[database]
[database.launcher]
  name = "launcher"

[api]
title = "ETL Pipeline Launcher API"
port = 5000
prefix = "/api/v{:d}"
version_str = "v{:d}"
version = 1
doc_path = "/api/doc"
include_default_error_message = false

[mailhog]
host = "etl-pipeline-launcher-mail"
smtp_port = 11025
http_port = 18025

[redis]
host = "etl-pipeline-launcher-redis"
port = 6379

[rabbitmq]
host = "etl-pipeline-launcher-rabbitmq"
user = "admin"
password = "yvPZ6j9n4ZyhXJV2"
port = 5630
http_port = 8090

[mongodb]

[flask]
error_include_message = false
