[application]
id = "fc050f989329b47f861e5760c713c820"
root_dir = "/var/www"
logs_dir = "/log"
contexts_dir = "/var/www/src"
configs_dir = "/var/www/config"

[identity_access]
token_issuer = "http://localhost"
public_key_file = "/export/certs/identity_access.pem"

[api]
title = "ETL Pipeline Launcher API"
port = 5000
prefix = "/api/v{:d}"
version_str = "v{:d}"
version = 1
doc_path = "/api/doc"
include_default_error_message = false

[mailhog]
host = "nlp-mail"
smtp_port = 11025
http_port = 18025

[redis]
host = "nlp-redis"
port = 6379

[rabbitmq]
exchanges.publish = "etl_pipeline"
connection.host = "rabbitmq-server"
connection.user = "guest"
connection.password = "guest"
connection.port = 5672
connection.vhost = "/"

[mongodb]
connection.host = "mongodb-server"
connection.port = 27017

[flask]
error_include_message = false
flask_debug = false
