[application]
baseurl = "http://localhost"

[identity_access]
token_issuer = "http://localhost"
public_key_file = "/export/certs/identity_access.pem"

[database]
host = "etl-pipeline-launcher-mysql"
[database.launcher]
  user = "launcher"
  password = "wTUbtEmk2S6R"
