#!/bin/sh

MODIFIED_FILES=$(git diff --stat --cached --name-only -- `find . -name '*.py'` 2>&1)
if [ ! -z "$MODIFIED_FILES" ]
then
    black --line-length 79 $MODIFIED_FILES
    flake8 --ignore=E203,W503 $MODIFIED_FILES
    if [ $? -eq 0 ]
    then
        make unit-tests
    else
        exit 1
    fi
fi
