version: "3"

services:
  database:
    container_name: nlp-database-emagister.it
    hostname: nlp.mysql.emagister.it
    volumes:
      - ../../.mysql-data-emagister.it:/var/lib/mysql/
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=JzMn4q5VR5zb

  application:
    container_name: nlp-application-emagister.it
    environment:
      - SITE=emagister.it
    ports:
      - "5005:5000"

  worker:
    environment:
      - SITE=emagister.it
