version: "3"

services:
  database:
    container_name: nlp-database-emagister.it
    hostname: nlp.mysql.emagister.it
    volumes:
      - ../../.mysql-data-emagister.it:/var/lib/mysql/
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=JzMn4q5VR5zb

  application:
    container_name: nlp-application-emagister.it
    environment:
      - SITE=emagister.it
    ports:
      - "5005:5000"

  worker:
    environment:
      - SITE=emagister.it

  rabbitmq:
    container_name: nlp-rabbitmq-emagister.it
    hostname: rabbitmq-emagister.it
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=yvPZ6j9n4ZyhXJV2
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    container_name: nlp-redis-emagister.it
    hostname: redis-emagister.it
    ports:
      - "6378:6379"
    volumes:
      - ../../.redis-data-emagister.it:/redis-data

  mailhog:
    container_name: nlp-mail-emagister.it
    hostname: mail-emagister.it
    ports:
      - "11025:1025"
      - "18025:8025"

  mongo:
    container_name: nlp-mongodb-emagister.it
    hostname: mongodb-emagister.it
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aC4tYp9RUSWwvc5g

  mongo-express:
    container_name: nlp-mongo-express-emagister.it
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aC4tYp9RUSWwvc5g
      - ME_CONFIG_MONGODB_URL=mongodb://root:aC4tYp9RUSWwvc5g@mongo:27018/

networks:
  default:
    external:
      name: nlp_net
