version: "3"

services:
  application:
    environment:
      - ENVIRONMENT=development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  worker:
    environment:
      - ENVIRONMENT=development
networks:
  default:
    external:
      name: nlp_net
