version: "3"

services:
  application:
    build:
      args:
        REQUIREMENTS_FILE: requirements-devel.txt
    environment:
      - SITE=test
      - ENVIRONMENT=test
      - FLASK_ENV=test
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"

  static-analysis:
    build:
      context: ../..
      dockerfile: docker/services/application/Dockerfile
      args:
        REQUIREMENTS_FILE: requirements-devel.txt
    command: python -m pylint ./

  worker:
    environment:
      - ENVIRONMENT=test

networks:
  nlp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
