version: "3"

services:
  application:
    environment:
      - ENVIRONMENT=test
      - FLASK_ENV=test
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
  worker:
    environment:
      - ENVIRONMENT=test
