version: "3"

services:
  worker:
    build:
      context: ../..
      dockerfile: docker/services/application/Dockerfile
    command: /var/www/bin/run_workers.py
    depends_on:
      - rabbitmq
      - redis
      - mailhog
      - mongo
      - mongo-express
    networks:
      nlp_net:
        ipv4_address: 10.5.0.9

  rabbitmq:
    container_name: nlp-rabbitmq
    hostname: rabbitmq-server
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=yvPZ6j9n4ZyhXJV2
    networks:
      nlp_net:
        ipv4_address: 10.5.0.5
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: nlp-redis
    image: redis:alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    hostname: redis
    networks:
      nlp_net:
        ipv4_address: 10.5.0.4
    ports:
      - "6379:6379"
    volumes:
      - ../../.redis-data:/redis-data

  mailhog:
    container_name: nlp-mail
    image: mailhog/mailhog
    networks:
      nlp_net:
        ipv4_address: 10.5.0.6
    ports:
      - "11025:1025"
      - "18025:8025"

  mongo:
    build:
      context: ../services/mongodb
      dockerfile: Dockerfile
    image: mongo:5.0-focal
    container_name: nlp-mongodb
    hostname: mongodb-server
    restart: always
    networks:
      nlp_net:
        ipv4_address: 10.5.0.7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aC4tYp9RUSWwvc5g

  mongo-express:
    image: mongo-express:0.32
    container_name: nlp-mongo-express
    restart: always
    networks:
      nlp_net:
        ipv4_address: 10.5.0.8
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aC4tYp9RUSWwvc5g
      - ME_CONFIG_MONGODB_URL=mongodb://root:aC4tYp9RUSWwvc5g@mongo:27017/

networks:
  nlp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
