version: "3"

services:
  application:
    build:
      args:
        REQUIREMENTS_FILE: requirements-devel.txt
    environment:
      - ENVIRONMENT=development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  worker:
    environment:
      - ENVIRONMENT=development
